/*Create ORGANIZATION table*/
DROP TABLE IF EXISTS `ORGANIZATION`;
CREATE TABLE `ORGANIZATION`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(50) NOT NULL,
	`CODE` VARCHAR(20) NULL DEFAULT NULL,
	`ADDRESS` VARCHAR(128) NULL DEFAULT NULL,
	`DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
	`PHONE` VARCHAR(40) NULL DEFAULT NULL,
	`FAX` VARCHAR(40) NULL DEFAULT NULL,
	`WEB_SITE` VARCHAR(128) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NOT NULL
);

/*Create POSITION table*/
DROP TABLE IF EXISTS `POSITION`;
CREATE TABLE `POSITION`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(50) NOT NULL,
	`DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NOT NULL
);

/*Create USER_LOGIN TABLE*/
DROP TABLE IF EXISTS `USER_LOGIN`;
CREATE TABLE `USER_LOGIN`(
  `ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `LOGIN_ID` VARCHAR(64) NOT NULL,
  `NAME` VARCHAR(40) NULL DEFAULT NULL,
  `LOGIN_PASSWORD` VARCHAR(64) DEFAULT NULL,
  `EMAIL` VARCHAR(64) NOT NULL,
  `POSITION_ID` INT NOT NULL,
  `EMPLOY_DATE` DATE DEFAULT NULL,
  `CREATE_TIME` DATETIME NOT NULL,
  `ORG_ID` INT NULL,
  `OPER_ID` INT NULL
);

/*Create USER_LOGIN_EXT TABLE*/
DROP TABLE IF EXISTS `USER_LOGIN_EXT`;
CREATE TABLE `USER_LOGIN_EXT`(
  `ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `LOGIN_ID` VARCHAR(64) NOT NULL,
  `SEX` VARCHAR(40) NULL DEFAULT NULL,
  `BRITHDAY` DATE DEFAULT NULL,
  `THUMB` VARCHAR(64) NULL DEFAULT NULL,
  `PHONE` VARCHAR(20) NULL DEFAULT NULL,
  `ADDRESS` VARCHAR(64) DEFAULT NULL
);

/*Create DEPARTMENT TABLE*/
DROP TABLE IF EXISTS `DEPARTMENT`;
CREATE TABLE `DEPARTMENT`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(50) NOT NULL,
	`CODE` VARCHAR(20) NULL DEFAULT NULL,
	`DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

/*CREATE MAJOR TABLE*/
DROP TABLE IF EXISTS `MAJOR`;
CREATE TABLE `MAJOR`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(50) NOT NULL,
	`CODE` VARCHAR(20) NULL DEFAULT NULL,
	`DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

/*Create COURSE TABLE*/
DROP TABLE IF EXISTS `COURSE`;
CREATE TABLE `COURSE`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(50) NOT NULL,
	`CODE` VARCHAR(20) NULL DEFAULT NULL,
	`DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

/*Create GROUP TABLE*/
DROP TABLE IF EXISTS `CLUB`;
CREATE TABLE `CLUB`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(50) NOT NULL,
	`DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

/*Create ROLE TABLE*/
DROP TABLE IF EXISTS `ROLE`;
CREATE TABLE `ROLE`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(50) NOT NULL,
	`DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

/*Create PERMISSION TABLE*/
DROP TABLE IF EXISTS `PERMISSION`;
CREATE TABLE `PERMISSION`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(50) NOT NULL,
	`DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

/*Create DEPT_ORG TABLE*/
DROP TABLE IF EXISTS `DEPT_ORG`;
CREATE TABLE `DEPT_ORG`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`DEPT_ID` INT NULL DEFAULT NULL,
	`ORG_ID` INT NULL DEFAULT NULL
);

/*Create USER_LOGIN_ORG TABLE*/
DROP TABLE IF EXISTS `USER_LOGIN_ORG`;
CREATE TABLE `USER_LOGIN_ORG`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`MAJOR_ID` INT NULL DEFAULT NULL,
	`DEPT_ORG_ID` INT NULL DEFAULT NULL
);