/*Create ORGANIZATION table*/
DROP TABLE IF EXISTS `ORGANIZATION`;
CREATE TABLE `ORGANIZATION`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(50) NOT NULL,
	`CODE` VARCHAR(20) NULL DEFAULT NULL,
	`ADDRESS` VARCHAR(128) NULL DEFAULT NULL,
	`DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
	`PHONE` VARCHAR(40) NULL DEFAULT NULL,
	`FAX` VARCHAR(40) NULL DEFAULT NULL,
	`WEB_SITE` VARCHAR(128) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NOT NULL
);

/*Create POSITION table*/
DROP TABLE IF EXISTS `POSITION`;
CREATE TABLE `POSITION`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(50) NOT NULL,
	`DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NOT NULL
);

/*Create USER_LOGIN TABLE*/
DROP TABLE IF EXISTS `USER_LOGIN`;
CREATE TABLE `USER_LOGIN`(
  `ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `LOGIN_ID` VARCHAR(64) NOT NULL,
  `NAME` VARCHAR(40) NULL DEFAULT NULL,
  `LOGIN_PASSWORD` VARCHAR(64) DEFAULT NULL,
  `EMAIL` VARCHAR(64) NOT NULL,
  `POSITION_ID` INT NOT NULL,
  `EMPLOY_DATE` DATE DEFAULT NULL,
  `CREATE_TIME` DATETIME NOT NULL,
  `ORG_ID` INT NULL,
  `OPER_ID` INT NULL
);

/*Create USER_LOGIN_EXT TABLE*/
DROP TABLE IF EXISTS `USER_LOGIN_EXT`;
CREATE TABLE `USER_LOGIN_EXT`(
  `ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `LOGIN_ID` VARCHAR(64) NOT NULL,
  `SEX` VARCHAR(40) NULL DEFAULT NULL,
  `BRITHDAY` DATE DEFAULT NULL,
  `THUMB` VARCHAR(64) NULL DEFAULT NULL,
  `PHONE` VARCHAR(20) NULL DEFAULT NULL,
  `ADDRESS` VARCHAR(64) DEFAULT NULL
);

/*Create DEPARTMENT TABLE*/
DROP TABLE IF EXISTS `DEPARTMENT`;
CREATE TABLE `DEPARTMENT`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(50) NOT NULL,
	`CODE` VARCHAR(20) NULL DEFAULT NULL,
	`DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

/*CREATE MAJOR TABLE*/
DROP TABLE IF EXISTS `MAJOR`;
CREATE TABLE `MAJOR`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(50) NOT NULL,
	`CODE` VARCHAR(20) NULL DEFAULT NULL,
	`DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

/*Create COURSE TABLE*/
DROP TABLE IF EXISTS `COURSE`;
CREATE TABLE `COURSE`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(50) NOT NULL,
	`CODE` VARCHAR(20) NULL DEFAULT NULL,
	`DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

/*Create GROUP TABLE*/
DROP TABLE IF EXISTS `CLUB`;
CREATE TABLE `CLUB`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(50) NOT NULL,
	`DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

/*Create ROLE TABLE*/
DROP TABLE IF EXISTS `ROLE`;
CREATE TABLE `ROLE`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(50) NOT NULL,
	`DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

/*Create PERMISSION TABLE*/
DROP TABLE IF EXISTS `PERMISSION`;
CREATE TABLE `PERMISSION`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(50) NOT NULL,
	`DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

/*Create DEPT_ORG TABLE*/
DROP TABLE IF EXISTS `DEPT_ORG`;
CREATE TABLE `DEPT_ORG`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`DEPT_ID` INT NULL DEFAULT NULL,
	`ORG_ID` INT NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

/*Create MAJOR_DEPT TABLE*/
DROP TABLE IF EXISTS `MAJOR_DEPT`;
CREATE TABLE `MAJOR_DEPT`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`MAJOR_ID` INT NULL DEFAULT NULL,
	`DEPT_ID` INT NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

/*Create MAJOR_DEPT_ORG TABLE*/
DROP TABLE IF EXISTS `MAJOR_DEPT_ORG`;
CREATE TABLE `MAJOR_DEPT_ORG`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`MAJOR_DEPT_ID` INT NULL DEFAULT NULL,
	`ORG_ID` INT NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

/*Create USER_STUDENT_MAJOR TABLE*/
DROP TABLE IF EXISTS `USER_STUDENT_MAJOR`;
CREATE TABLE `USER_STUDENT_MAJOR`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`LOGIN_ID` INT NULL DEFAULT NULL,
	`MAJOR_DEPT_ID` INT NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

/*Create USER_TEACHER_DEPT TABLE*/
DROP TABLE IF EXISTS `USER_TEACHER_DEPT`;
CREATE TABLE `USER_TEACHER_DEPT`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`LOGIN_ID` INT NULL DEFAULT NULL,
	`DEPT_ORG_ID` INT NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

/*Create USER_ADMIN_ORG TABLE*/
DROP TABLE IF EXISTS `USER_ADMIN_ORG`;
CREATE TABLE `USER_ADMIN_ORG`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`LOGIN_ID` INT NULL DEFAULT NULL,
	`ORG_ID` INT NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

/*Create TEACHER_COURSE TABLE*/
DROP TABLE IF EXISTS `TEACHER_COURSE`;
CREATE TABLE `TEACHER_COURSE`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`LOGIN_ID` INT NULL DEFAULT NULL,
	`COURSE_ID` INT NULL DEFAULT NULL,
	`GRADE` VARCHAR(10) NULL DEFAULT NULL,
	`TERM` VARCHAR(2) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

/*Create STUDENT_COURSE TABLE*/
DROP TABLE IF EXISTS `STUDENT_COURSE`;
CREATE TABLE `STUDENT_COURSE`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`LOGIN_ID` INT NULL DEFAULT NULL,
	`TEACHER_COURSE_ID` INT NULL,
	`SCORE` VARCHAR(10) NULL DEFAULT NULL,
	`SETNUM` INT(5) NULL DEFAULT NULL,
	`TEACHER_COURSE_GROUP_ID` INT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

/*Create TEACHER_COURSE_GROUP TABLE*/
DROP TABLE IF EXISTS `TEACHER_COURSE_GROUP`;
CREATE TABLE `TEACHER_COURSE_GROUP`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(40) NULL DEFAULT NULL,
	`TEACHER_COURSE_ID` INT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

DROP TABLE IF EXISTS `STUDENT_COURSE_GROUP`;
CREATE TABLE `STUDENT_COURSE_GROUP`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`STUDENT_ID` INT NULL,
	`TEACHER_COURSE_GROUP_ID` INT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

/*Create USER_LOGIN_ORG TABLE
DROP TABLE IF EXISTS `USER_LOGIN_ORG`;
CREATE TABLE `USER_LOGIN_ORG`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`MAJOR_ID` INT NULL DEFAULT NULL,
	`DEPT_ORG_ID` INT NULL DEFAULT NULL
);*/

/*Create ROLE TABLE*/
DROP TABLE IF EXISTS `RESOURCE`;
CREATE TABLE `RESOURCE`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(50) NOT NULL,
	`DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

DROP TABLE IF EXISTS `MEDIA_CATEGORY`;
CREATE TABLE `MEDIA_CATEGORY`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(50) NOT NULL,
	`DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

DROP TABLE IF EXISTS `MEDIA_TAG`;
CREATE TABLE `MEDIA_TAG`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(50) NOT NULL,
	`DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

DROP TABLE IF EXISTS `MEDIA_RESOURCE`;
CREATE TABLE `MEDIA_RESOURCE`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(50) NOT NULL,
	`URL` VARCHAR(255) NULL DEFAULT NULL,
	`type` VARCHAR(20) NULL,
	`CID` INT NULL,
	`DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`OPER_ID` INT NULL
);

DROP TABLE IF EXISTS `MEDIA_TAG_MAP`;
CREATE TABLE `MEDIA_TAG_MAP`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`MEDIA_ID` INT NULL,
	`MEDIA_TAG_ID` INT NULL
);